### ISSUE TITLE
Enhance mix of diffuse and specular for Cook-Torrance PBR materials.

### ISSUE THREAD

**Issue by JacquesDiringer** [JacquesDiringer/GLEngine#3]
This can easily be done by also taking the diffuse value into account (with the RGB converted to luminance) rather than only the specular one.

**Comment by theblackunknown** [comment]
Are you targetting a specific shader for this issue or any which blend diffuse and specular contribution ?

**Comment by JacquesDiringer** [comment]
I was actually targeting my EnvmapLight shader that uses the precomputed 3D envmaps (blurred several times according to a roughness defined by the Cook-Torrance model).
The shader mixes diffuse and specular by only looking at the specular, which seems wrong.
